# Generated by Django 4.2 on 2023-10-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='discord',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
